server:
  port: 8080

logging:
  level:
    root:
      debug
spring:
  main:
    banner-mode: console
  datasource:
    url:
      jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: